import os

env = os.environ.get

# PRINT_FLAG = env("PRINT_FLAG", True)
WEBSOCKETSERVERHOST = env("WEBSOCKETSERVERHOST", "0.0.0.0")
WEBSOCKETSERVERPORT = env("WEBSOCKETSERVERPORT", 8888)
WEBSOCKETSERVERCONNECTIONS = env("WEBSOCKETSERVERCONNECTIONS", 50)